version: "3"

services:
  api:
    build:
      context: .
    depends_on:
      - db
    container_name: lng_api
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    expose:
      - "5000"
    links:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.database
    container_name: lng_db
    environment:
      - POSTGRES_DB=lng_dev
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mysecretpassword